environments:
    - name: prod
      configs:
          deploymentEnvironments:
              - displayOnDevportal: true
                deploymentEnvironment: Default
                deploymentVhost: localhost
          policies:
              - Gold
              - Silver 
    - name: test
      configs:
          deploymentEnvironments:
              - displayOnDevportal: true
                deploymentEnvironment: Default
                deploymentVhost: localhost
          policies:
              - Gold
              - Silver  
          security:
              production:
                  enabled: true
                  type: basic
                  username: admin
                  password: admin     
